name: Build the book
on: workflow_dispatch

jobs:
  texlive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19.2
      - name: Run pandoc
        run: pandoc --version
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install pandoc-fignos
        run: pip install pandoc-fignos
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            scheme-basic latexmk collection-xetex
      - name: Use TeX Live
        run: |
          git submodule update --init --recursive
          ./build-book.sh
          cd book
          latexmk -f -pdf -silent book.tex
