name: Build the book
on: workflow_dispatch

jobs:
  texlive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install latest pandoc
        uses: pandoc/actions/setup@{main}
      - name: Run pandoc
        run: pandoc --version
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            scheme-basic latexmk collection-xetex
      - name: Use TeX Live
        run: |
          ./make-latex.sh
