name: Build the book
on: workflow_dispatch

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pandoc v2 (fignos requirement)
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19.2
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install pandoc-fignos
        run: pip install pandoc-fignos
      - name: Assemble latex files
        run: |
          git submodule update --init --recursive
          ./build-book.sh
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            scheme-basic latexmk collection-xetex etoolbox euenc filehook fontspec makecmds polyglossia tipa xkeyval xunicode mktexlsr updmap-sys metalogo xltxtra sectsty ulem biblatex logreq csquotes tocloft biber hyphenat nowidow microtype titling emptypage float caption enumitem babel babel-greek bookmark dvipdfmx firstaid greek-fontenc hyperref 
      - name: Use TeX Live
        run: |
          cd book
          latexmk -f -xelatex -silent book.tex
